
// Generated by https://quicktype.io

export interface ArroyoPoint {
  id:              number;
  tweet:           string;
  direccion_tweet: string;
  latitud:         string;
  longitud:        string;
}
